LOCAL_PATH := $(call my-dir)

# 转码AVILib
MY_AVILIB_SRC_FILES := avilib.c platform_posix.c
MY_AVILIB_C_INCLUDES := $(LOCAL_PATH)

include $(CLEAR_VARS)

LOCAL_MODULE := avilib_static
LOCAL_SRC_FILES := $(MY_AVILIB_SRC_FILES)
# 包含导出路径
LOCAL_EXCEPORT_C_INCLUDES := $(MY_AVILIB_C_INCLUDES)

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := avilib_shared
LOCAL_SRC_FILES := $(MY_AVILIB_SRC_FILES)
# 包含导出路径
LOCAL_EXCEPORT_C_INCLUDES := $(MY_AVILIB_C_INCLUDES)

include $(BUILD_SHARED_LIBRARY)