/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_zvideo_NativeWindowPlayerActivity */

#ifndef _Included_com_ziv_zvideo_NativeWindowPlayerActivity
#define _Included_com_ziv_zvideo_NativeWindowPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_zvideo_NativeWindowPlayerActivity
 * Method:    init
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_ziv_zvideo_NativeWindowPlayerActivity_init
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_ziv_zvideo_NativeWindowPlayerActivity
 * Method:    render
 * Signature: (JLandroid/view/Surface;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ziv_zvideo_NativeWindowPlayerActivity_render
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
